export const LOGIN_INTO = 'LOGIN_INTO';
export const LOG_OUT = 'LOG_OUT';
export const UPDATE_COMPONENT_ABLE = 'UPDATE_COMPONENT_ABLE';
export const UPDATE_COMPONENT_DISABLE = 'UPDATE_COMPONENT_DISABLE';